# Generated by Django 6.0 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0054_bookmarkbundle_filter_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="link_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="link_status",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
