# Generated by Django 6.0 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0055_bookmark_link_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="remind_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
